/* This schema is built from an older version of the Stack Exhcange Data Dump: https://archive.org/details/stackexchange

The schema has been adapted to postgresql

This is shared under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) https://creativecommons.org/licenses/by-sa/4.0/

*/

CREATE TABLE Badges (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	Name varchar(40) NOT NULL,
	UserId int NOT NULL,
	Date timestamp(0) NOT NULL
);


CREATE TABLE Comments (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	CreationDate timestamp(0) NOT NULL,
	PostId int NOT NULL,
	Score int NULL,
	Text varchar(700) NOT NULL,
	UserId int NULL
);

CREATE TABLE LinkTypes (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	Type varchar(50) NOT NULL
);

CREATE TABLE PostLinks (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	CreationDate timestamp(0) NOT NULL,
	PostId int NOT NULL,
	RelatedPostId int NOT NULL,
	LinkTypeId int NOT NULL
);

CREATE TABLE Posts (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	AcceptedAnswerId int NULL,
	AnswerCount int NULL,
	Body text NOT NULL,
	ClosedDate timestamp(0) NULL,
	CommentCount int NULL,
	CommunityOwnedDate timestamp(0) NULL,
	CreationDate timestamp(0) NOT NULL,
	FavoriteCount int NULL,
	LastActivityDate timestamp(0) NOT NULL,
	LastEditDate timestamp(0) NULL,
	LastEditorDisplayName varchar(40) NULL,
	LastEditorUserId int NULL,
	OwnerUserId int NULL,
	ParentId int NULL,
	PostTypeId int NOT NULL,
	Score int NOT NULL,
	Tags varchar(150) NULL,
	Title varchar(250) NULL,
	ViewCount int NOT NULL
);


CREATE TABLE PostTypes (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	Type varchar(50) NOT NULL
);

CREATE TABLE Users (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	AboutMe text NULL,
	Age int NULL,
	CreationDate timestamp(0) NOT NULL,
	DisplayName varchar(40) NOT NULL,
	DownVotes int NOT NULL,
	EmailHash varchar(40) NULL,
	LastAccessDate timestamp(0) NOT NULL,
	Location varchar(100) NULL,
	Reputation int NOT NULL,
	UpVotes int NOT NULL,
	Views int NOT NULL,
	WebsiteUrl varchar(200) NULL,
	AccountId int NULL
);

CREATE TABLE Votes (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	PostId int NOT NULL,
	UserId int NULL,
	BountyAmount int NULL,
	VoteTypeId int NOT NULL,
	CreationDate timestamp(0) NOT NULL
);

CREATE TABLE VoteTypes (
	Id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE PRIMARY KEY,
	Name varchar(50) NOT NULL
);